# Compose file used for local development

services:
  postgres:
    extends:
      file: compose.base.yml
      service: postgres
    env_file:
      - envs/common_dev.env
  redis:
    extends:
      file: compose.base.yml
      service: redis
    env_file:
      - envs/common_dev.env
  backend:
    extends:
      file: compose.base.yml
      service: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - envs/common_dev.env
  dramatiq:
    extends:
      file: compose.base.yml
      service: dramatiq
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - envs/common_dev.env
  frontend:
    extends:
      file: compose.base.yml
      service: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    env_file:
      - envs/common_dev.env

volumes:
  postgres_data:
  redis_data:
