# Compose file used for local development

services:
  postgres:
    extends:
      file: compose.base.yml
      service: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  backend:
    extends:
      file: compose.base.yml
      service: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - envs/common_dev.env

  frontend:
    extends:
      file: compose.base.yml
      service: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - envs/common_dev.env

volumes:
  postgres_data:
