services:
  postgres:
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  backend:
    container_name: fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - envs/common_dev.env
    environment:
      GEMINI_API_KEY:
      LOCAL_ARCHIVE_FOLDER: /tmp/archive_folder

  frontend:
    container_name: nextjs_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - envs/common_dev.env

networks:
  app_network:
    driver: bridge