"""added views count

Revision ID: 04530fc768de
Revises: ed559a496395
Create Date: 2025-05-31 10:19:41.052080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04530fc768de"
down_revision: Union[str, None] = "ed559a496395"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parsed_news",
        sa.Column("view_count", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parsed_news", "view_count")
    # ### end Alembic commands ###
