"""added importancy of parsed news

Revision ID: 1473bcdf4d4c
Revises: 04530fc768de
Create Date: 2025-08-14 22:31:18.845661

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1473bcdf4d4c"
down_revision: str | None = "dfe1ce1233b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("parsed_news", sa.Column("importancy", sa.Integer(), server_default="5", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parsed_news", "importancy")
    # ### end Alembic commands ###
