"""added deletion links

Revision ID: 16e54104edeb
Revises: c98f0fb7c230
Create Date: 2025-10-18 18:38:49.730601

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16e54104edeb"
down_revision: str | None = "c98f0fb7c230"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_deletion_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer()),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["public.accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_deletion_tokens_account_id"), "account_deletion_tokens", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_account_deletion_tokens_expires_at"), "account_deletion_tokens", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_account_deletion_tokens_token_hash"), "account_deletion_tokens", ["token_hash"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_account_deletion_tokens_token_hash"), table_name="account_deletion_tokens")
    op.drop_index(op.f("ix_account_deletion_tokens_expires_at"), table_name="account_deletion_tokens")
    op.drop_index(op.f("ix_account_deletion_tokens_account_id"), table_name="account_deletion_tokens")
    op.drop_table("account_deletion_tokens")
    # ### end Alembic commands ###
