"""added picks

Revision ID: 4d99410192dd
Revises: 04530fc768de
Create Date: 2025-08-05 18:42:52.286439

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d99410192dd"
down_revision: str | None = "04530fc768de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "news_picks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["public.accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "news_pick_items",
        sa.Column("pick_id", sa.Integer(), nullable=False),
        sa.Column("parsed_news_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parsed_news_id"],
            ["public.parsed_news.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pick_id"],
            ["public.news_picks.id"],
        ),
        sa.PrimaryKeyConstraint("pick_id", "parsed_news_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("news_pick_items")
    op.drop_table("news_picks")
    op.drop_table("accounts")
    # ### end Alembic commands ###
