"""renamed date in news pick and unique attributes

Revision ID: dfe1ce1233b2
Revises: 4d99410192dd
Create Date: 2025-08-08 22:55:21.062017

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dfe1ce1233b2"
down_revision: str | None = "4d99410192dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "accounts", ["email"])

    # Rename 'date' column to 'created_at' (preserves values)
    op.alter_column("news_picks", "date", new_column_name="created_at")

    op.create_unique_constraint(None, "news_picks", ["hash"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Rename 'created_at' back to 'date' (preserves values)
    op.drop_constraint('uq_news_picks_hash', 'news_picks', type_='unique')
    op.alter_column('news_picks', 'created_at', new_column_name='date')
    op.drop_constraint('uq_accounts_email', 'accounts', type_='unique')
    # ### end Alembic commands ###
