"""Change InputNews model

Revision ID: ed559a496395
Revises: 54ac58121805
Create Date: 2025-04-18 14:55:50.219895

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ed559a496395"
down_revision: Union[str, None] = "54ac58121805"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "input_news",
        sa.Column("tags", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "input_news",
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "input_news",
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "input_news",
        sa.Column("source_site", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "input_news",
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "input_news",
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "input_news",
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "input_news",
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "input_news", sa.Column("publication_date", sa.DateTime(), nullable=True)
    )
    op.drop_column("input_news", "processed_at")
    op.drop_column("input_news", "source")
    op.drop_column("input_news", "raw_metadata")
    op.drop_column("input_news", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "input_news",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "input_news",
        sa.Column(
            "raw_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "input_news",
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "input_news",
        sa.Column(
            "processed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("input_news", "publication_date")
    op.drop_column("input_news", "title")
    op.drop_column("input_news", "content")
    op.drop_column("input_news", "author")
    op.drop_column("input_news", "summary")
    op.drop_column("input_news", "source_site")
    op.drop_column("input_news", "source_url")
    op.drop_column("input_news", "category")
    op.drop_column("input_news", "tags")
    # ### end Alembic commands ###
